;;; create.lisp - Ticket creation command

(in-package :ticket)

(defstruct create-options
  (title "Untitled")
  (description nil)
  (design nil)
  (acceptance nil)
  (ticket-type "task")
  (priority 2)
  (assignee nil)
  (external-ref nil)
  (parent nil))

(defun parse-create-args (args)
  "Parse command line arguments for create command."
  (let ((options (make-create-options))
        (i 0))
    (let ((git-user (get-git-user-name)))
      (when git-user (setf (create-options-assignee options) git-user)))
    (loop while (< i (length args))
          for arg = (nth i args)
          do (cond
               ((or (string= arg "-d") (string= arg "--description"))
                (incf i)
                (when (< i (length args))
                  (setf (create-options-description options) (nth i args))))
               ((string= arg "--design")
                (incf i)
                (when (< i (length args))
                  (setf (create-options-design options) (nth i args))))
               ((string= arg "--acceptance")
                (incf i)
                (when (< i (length args))
                  (setf (create-options-acceptance options) (nth i args))))
               ((or (string= arg "-t") (string= arg "--type"))
                (incf i)
                (when (< i (length args))
                  (setf (create-options-ticket-type options) (nth i args))))
               ((or (string= arg "-p") (string= arg "--priority"))
                (incf i)
                (when (< i (length args))
                  (setf (create-options-priority options)
                        (parse-integer (nth i args) :junk-allowed t))))
               ((or (string= arg "-a") (string= arg "--assignee"))
                (incf i)
                (when (< i (length args))
                  (setf (create-options-assignee options) (nth i args))))
               ((string= arg "--external-ref")
                (incf i)
                (when (< i (length args))
                  (setf (create-options-external-ref options) (nth i args))))
               ((string= arg "--parent")
                (incf i)
                (when (< i (length args))
                  (setf (create-options-parent options) (nth i args))))
               ((string-starts-with arg "-") nil)
               (t (setf (create-options-title options) arg)))
             (incf i))
    options))

(defun generate-ticket-content (id options)
  "Generate ticket file content."
  (with-output-to-string (s)
    (format s "---~%")
    (format s "id: ~A~%" id)
    (format s "status: open~%")
    (format s "deps: []~%")
    (format s "links: []~%")
    (format s "created: ~A~%" (iso-timestamp))
    (format s "type: ~A~%" (create-options-ticket-type options))
    (format s "priority: ~A~%" (create-options-priority options))
    (when (create-options-assignee options)
      (format s "assignee: ~A~%" (create-options-assignee options)))
    (when (create-options-external-ref options)
      (format s "external-ref: ~A~%" (create-options-external-ref options)))
    (when (create-options-parent options)
      (format s "parent: ~A~%" (create-options-parent options)))
    (format s "---~%")
    (format s "# ~A~%~%" (create-options-title options))
    (when (create-options-description options)
      (format s "~A~%~%" (create-options-description options)))
    (when (create-options-design options)
      (format s "## Design~%~%~A~%~%" (create-options-design options)))
    (when (create-options-acceptance options)
      (format s "## Acceptance Criteria~%~%~A~%~%" (create-options-acceptance options)))))

(defun cmd-create (args)
  "Create ticket, print ID. Returns 0 on success."
  (handler-case
      (progn
        (ensure-tickets-dir)
        (let* ((options (parse-create-args args))
               (id (generate-id))
               (content (generate-ticket-content id options))
               (file-path (ticket-file-path id)))
          (write-file-contents file-path content)
          (format t "~A~%" id)
          0))
    (error (e)
      (format *error-output* "Error: ~A~%" e)
      1)))
